/**
 * The Fold mark.
 *
 * The church, matching the brand files in public/brand exactly. It used to
 * be a plain house outline with an arched door, which read as a generic
 * home icon and did not match anything we sent anybody.
 *
 * `showTagline` is off by default so the mark can sit in the app header
 * without repeating the pitch on every page.
 *
 * `variant="light"` is for a dark ground, such as the panel beside the
 * sign in form, where the brand purple on deep purple would disappear.
 */
export function Logo({
  showTagline = false,
  size = "md",
  variant = "default",
}: {
  showTagline?: boolean;
  size?: "sm" | "md" | "lg";
  variant?: "default" | "light";
}) {
  const markClass = variant === "light" ? "text-white" : "text-primary";
  const wordClass = variant === "light" ? "text-white" : "text-foreground";
  const taglineClass =
    variant === "light" ? "text-white/70" : "text-muted-foreground";
  const dims =
    size === "lg" ? 40 : size === "sm" ? 24 : 30;
  const wordmark =
    size === "lg" ? "text-3xl" : size === "sm" ? "text-base" : "text-xl";

  return (
    <span className="inline-flex items-center gap-2.5">
      <svg
        width={dims}
        height={dims}
        viewBox="0 0 120 120"
        fill="none"
        aria-hidden="true"
        className="shrink-0"
      >
        {/*
          The church, simplified, generated by scripts/build-mark.mjs and
          pasted here. The full mark in public/brand carries the side
          windows, the rose window and the gable window; below about 40px
          those close into a smudge, and the header renders at 24 to 40.

          Same building, less detail, not a second idea. If the mark ever
          changes, change it in that script and paste the output here rather
          than editing these numbers: every junction in it is computed and
          asserted, and hand editing is what put seven joints out of true
          the first time.
        */}
        <g
          stroke="currentColor"
          strokeWidth="5"
          strokeLinecap="round"
          strokeLinejoin="round"
          className={markClass}
        >
          <path d="M60 6V20M53 12h14" />
          <path d="M46 36 60 20l14 16" />
          <path d="M52 29.1V55.5M68 29.1V55.5" />
          <path d="M30 76 60 48l30 28" />
          <path d="M40 66.7V106M80 66.7V106" />
          <path d="M50 106V91a10 10 0 0 1 20 0V106" />
          <path d="M40 80 14 92M18 90.2V106" />
          <path d="M80 80 106 92M102 90.2V106" />
          <path d="M10 106h100" />
        </g>
      </svg>

      <span className="flex flex-col leading-none">
        <span
          className={`${wordmark} font-bold tracking-tight ${wordClass}`}
        >
          Fold
        </span>
        {showTagline && (
          <span className={`mt-1 text-[11px] font-medium uppercase tracking-[0.16em] ${taglineClass}`}>
            Know your flock
          </span>
        )}
      </span>
    </span>
  );
}
